server.port=8080
spring.application.name=spring-gateway
orders.uri=${ORDERS_URI}
payments.uri=${PAYMENTS_URI}
context.path=${CONTEXT_PATH}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
spring.cloud.discovery.client.composite-indicator.enabled=false
spring.cloud.discovery.enabled=false
management.endpoint.health.status.order=DOWN,OUT_OF_SERVICE,UNKNOWN,UP

security.jwt.secret-key=${JWT_SECRET}